stages:
  - integration
  - build
  - test
  - deploy

variables:
  SOURCE_REPOSITORY: https://github.com/Joginator4/nginx-measurement.git
  MASTER_NODE_PRIVATE_KEY: $MASTER_NODE_PRIVATE_KEY

repo_integration:
  stage: integration
  tags:
    - bastion
    - shell
  before_script:
    - echo $MASTER_NODE_PRIVATE_KEY
#    - echo $MASTER_NODE_PRIVATE_KEY | sed -e "s/-----BEGIN OPENSSH PRIVATE KEY-----/&\n/" -e "s/-----END OPENSSH PRIVATE KEY-----/&\n/" -e "s/\S\{64\}/&\n/g"\ > deploy-key.pem
    - chmod 400 $MASTER_NODE_PRIVATE_KEY
#    - cat deploy-key.pem
  script:
         - ssh -o StrictHostKeyChecking=no -i $MASTER_NODE_PRIVATE_KEY vagrant@$MASTER_IP_ADDRESS
         - ls