replicas: 1

containers:
  name: nginx-server
  repo: nginx-measurement/nginx
  image: nginx-server
  tag: 1.0
  imagePullSecrets: microservice-docker-registry
  imagePullPolicy: IfNotPresent
  container_port: 80

imageCredentials:
  registry: registry.gitlab.com/polyrepo_microservices/nginx-measurement/
  username: admin
  password: admin123

resources:
  limits:
    memory: 4Gi
  requests:
    memory: 1Gi

NodeSelector: worker-node01