apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-server-{{ .Release.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      imagePullPolicy: {{ .Values.containers.imagePullPolicy }}
      containers:
      - name: {{ .Values.containers.name }}
        image: nginx
        ports:
        - containerPort: {{ .Values.containers.container_port }}
      resources:
        limits:
          memory: {{ .Values.resources.limits.memory }}
        requests:
          memory: {{ .Values.resources.requests.memory }}
      volumeMounts:
      - name: nginx-volume
        mountPath: /etc/nginx/nginx.conf
        subPath: nginx.conf
      volumes:
      - name: nginx-configmap
        configMap:
          name: nginx-configmap
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.NodeSelector }}