containers:
  name: gobench-client
  repo: registry.gitlab.com/polyrepo_microservices/nginx-measurement
  image_name: gobench
  image_tag: "1.0.62"
  imagePullPolicy: IfNotPresent
  imagePullSecrets:
    name: microservice-docker-registry
  restartPolicy: Never

# Username and password are not real here , password are provided in pipeline to be dont shared !

imageCredentials:
  registry: registry.gitlab.com/polyrepo_microservices/nginx-measurement/
  username: admin
  password: admin123

securityContext:
  allowPrivilegeEscalation: true
  privileged: true
  runAsUser: 0

env:
  NODE_SELECTOR: worker-node01
  SERVER_IP: "192.168.0.0"

## This is name of folder which files are extracted in bastion host ##

folder:
  name: /home/vagrant/logs/nginx_measurement


sshpass:
  rsync_server_ip: ""
  rsync_server_login: ""
  rsync_server_password: ""