apiVersion: batch/v1
kind: Job
metadata:
  name: gobench-client-{{ .Release.Name }}
  labels:
    app: gobench-client
spec:
  template:
    metadata:
      annotations:
    spec:
      containers:
      - name: {{ .Values.image.name }}
        image: {{ .Values.image.repo }}/{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.ImagePullPolicy}}
        securityContext:
          allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalataion }}
          privileged: {{ .Values.securityContext.privileged }}
          runAsUser: {{ .Values.securityContext.runAsUser }}
        command: [ "/bin/bash", "-c"]
        args:
          - |
            /usr/local/bin/gobench -t 60 -c 100 -u http://{{ .Values.env.SERVER_IP }}/  > /mnt/result.txt
            sshpass -p {{ .Values.sshpass.rsync_password }} scp -q -o StrictHostKeyChecking=no /mnt/result.txt {{ .Values.sshpass.rsync_server }}/{{ .Values.scenario.name }}
            cat /mnt/result.txt
      imagePullSecrets:
            - name: repo-secret-{{ .Release.Name }}
      restartPolicy: {{ .Values.image.restartPolicy }}
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.env.NODE_SELECTOR }}